name: cogniguard-prod
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - pip
  - pip:
    - fastapi==0.115.5
    - uvicorn==0.34.0
    - streamlit==1.40.0
    - transformers==4.47.0
    - sentence-transformers==3.3.1
    - pandas==2.2.3
    - plotly==5.24.1
    - requests==2.32.3
    - pydantic==2.10.3